# Generated by Django 5.0.2 on 2024-03-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRUD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('level', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
